boxen::bin should depend on boxen::repo
bin/boxen depends on the boxen repo being cloned

Error: Could not find dependency Exec[clone /opt/boxen/repo] for
File[/opt/boxen/bin/boxen]